In [1]:
!pip install matplotlib.pyplot

Defaulting to user installation because normal site-packages is not writeable

ERROR: Could not find a version that satisfies the requirement matplotlib.pyplot (from versions: none)
ERROR: No matching distribution found for matplotlib.pyplot

In [ ]:
""" Just some notes from the cleaing
Row Number 350085 Column amount: 67
not all locations are places, some are just categories like high income
list of others OtherL_df=['High income','Low income', 'Lower middle income','Upper middle income' ]
"""

In [97]:
# Import necessary libraries
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load the Titanic dataset. Replace 'titanic.csv' with your own dataset file for your project.
# Ensure the dataset file exists and is in the same directory as this jupyter notebook.
Covid_df = pd.read_csv('newcovid.csv')
Air_df = pd.read_csv('Air Quality(Back Up).csv')

temp_df=['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa',
       'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda',
       'Argentina', 'Armenia', 'Aruba', 'Asia', 'Australia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'England', 'Equatorial Guinea', 'Eritrea',
       'Estonia', 'Eswatini', 'Ethiopia', 'Europe', 'European Union',
       'Faeroe Islands', 'Falkland Islands', 'Fiji', 'Finland', 'France',
       'French Guiana', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'High income', 'Honduras',
       'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
       'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania',
       'Low income', 'Lower middle income', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (country)', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria']
# Display the first few rows of the dataframe to ensure it is loaded correctly
nCovid_df = (Covid_df.fillna(0))

World_df=(Covid_df[Covid_df['location'].str.contains('World')])
Date_df=(nCovid_df[nCovid_df['date'].str.contains('2023-10-14')])
UN_df=(nCovid_df[nCovid_df['location'].str.contains('High income')])
ls_df=(nCovid_df[~nCovid_df['location'].str.contains('|'.join(temp_df), na=False)])

display(Date_df['total_cases'].sum())
print(UN_df.tail(15))
print(Date_df)
display(World_df[World_df['total_cases']>100])
display(ls_df['location'].unique())


display(Covid_df.columns)
s_df=(Covid_df['new_cases'].max())
display(Covid_df['total_cases'].unique)
display(Covid_df.loc[100, 'new_cases'])
display(Covid_df[Covid_df['new_cases']==8401961.0])
print(s_df)
#display(Covid_df.sort_values('location'))
display(Covid_df.groupby('total_cases'))

C:\Users\longs\AppData\Local\Temp\ipykernel_9204\1280786282.py:49: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  ls_df=(nCovid_df[~nCovid_df['location'].str.contains('|'.join(temp_df), na=False)])

np.float64(3268614575.0)

        iso_code continent     location        date  total_cases  new_cases  \
134294  OWID_HIC         0  High income  2023-10-09  425955807.0    32441.0
134295  OWID_HIC         0  High income  2023-10-10  425962863.0     7056.0
134296  OWID_HIC         0  High income  2023-10-11  425975299.0    12436.0
134297  OWID_HIC         0  High income  2023-10-12  425985054.0     9755.0
134298  OWID_HIC         0  High income  2023-10-13  425987511.0     2457.0
134299  OWID_HIC         0  High income  2023-10-14  425988267.0      756.0
134300  OWID_HIC         0  High income  2023-10-15  425988398.0      131.0
134301  OWID_HIC         0  High income  2023-10-16  425988398.0        0.0
134302  OWID_HIC         0  High income  2023-10-17  425988398.0        0.0
134303  OWID_HIC         0  High income  2023-10-18  425988398.0        0.0
134304  OWID_HIC         0  High income  2023-10-19          0.0        0.0
134305  OWID_HIC         0  High income  2023-10-20          0.0        0.0
134306  OWID_HIC         0  High income  2023-10-21          0.0        0.0
134307  OWID_HIC         0  High income  2023-10-22          0.0        0.0
134308  OWID_HIC         0  High income  2023-10-23          0.0        0.0

        new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
134294           13636.571     2914120.0        41.0               43.571
134295           13558.143     2914177.0        57.0               37.714
134296           13170.857     2914208.0        31.0               38.000
134297           12979.286     2914234.0        26.0               39.429
134298           11779.286     2914267.0        33.0               35.286
134299           10501.143     2914268.0         1.0               31.429
134300            9290.286     2914272.0         4.0               27.571
134301            4655.857     2914272.0         0.0               21.714
134302            3647.857     2914272.0         0.0               13.571
134303            1871.286     2914272.0         0.0                9.143
134304               0.000           0.0         0.0                0.000
134305               0.000           0.0         0.0                0.000
134306               0.000           0.0         0.0                0.000
134307               0.000           0.0         0.0                0.000
134308               0.000           0.0         0.0                0.000

        ...  male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
134294  ...           0.0                     0.0                         0.0
134295  ...           0.0                     0.0                         0.0
134296  ...           0.0                     0.0                         0.0
134297  ...           0.0                     0.0                         0.0
134298  ...           0.0                     0.0                         0.0
134299  ...           0.0                     0.0                         0.0
134300  ...           0.0                     0.0                         0.0
134301  ...           0.0                     0.0                         0.0
134302  ...           0.0                     0.0                         0.0
134303  ...           0.0                     0.0                         0.0
134304  ...           0.0                     0.0                         0.0
134305  ...           0.0                     0.0                         0.0
134306  ...           0.0                     0.0                         0.0
134307  ...           0.0                     0.0                         0.0
134308  ...           0.0                     0.0                         0.0

        life_expectancy  human_development_index    population  \
134294              0.0                      0.0  1.250515e+09
134295              0.0                      0.0  1.250515e+09
134296              0.0                      0.0  1.250515e+09
134297              0.0                      0.0  1.250515e+09
134298              0.0                      0.0  1.250515e+09
134299              0.0                      0.0  1.250515e+09
134300              0.0                      0.0  1.250515e+09
134301              0.0                      0.0  1.250515e+09
134302              0.0                      0.0  1.250515e+09
134303              0.0                      0.0  1.250515e+09
134304              0.0                      0.0  1.250515e+09
134305              0.0                      0.0  1.250515e+09
134306              0.0                      0.0  1.250515e+09
134307              0.0                      0.0  1.250515e+09
134308              0.0                      0.0  1.250515e+09

        excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
134294                                   0.0                          0.0
134295                                   0.0                          0.0
134296                                   0.0                          0.0
134297                                   0.0                          0.0
134298                                   0.0                          0.0
134299                                   0.0                          0.0
134300                                   0.0                          0.0
134301                                   0.0                          0.0
134302                                   0.0                          0.0
134303                                   0.0                          0.0
134304                                   0.0                          0.0
134305                                   0.0                          0.0
134306                                   0.0                          0.0
134307                                   0.0                          0.0
134308                                   0.0                          0.0

        excess_mortality  excess_mortality_cumulative_per_million
134294               0.0                                      0.0
134295               0.0                                      0.0
134296               0.0                                      0.0
134297               0.0                                      0.0
134298               0.0                                      0.0
134299               0.0                                      0.0
134300               0.0                                      0.0
134301               0.0                                      0.0
134302               0.0                                      0.0
134303               0.0                                      0.0
134304               0.0                                      0.0
134305               0.0                                      0.0
134306               0.0                                      0.0
134307               0.0                                      0.0
134308               0.0                                      0.0

[15 rows x 67 columns]
        iso_code continent           location        date  total_cases  \
1380         AFG      Asia        Afghanistan  2023-10-14     226813.0
2765    OWID_AFR         0             Africa  2023-10-14   13113845.0
4150         ALB    Europe            Albania  2023-10-14     334090.0
5535         DZA    Africa            Algeria  2023-10-14     271945.0
6920         ASM   Oceania     American Samoa  2023-10-14       8359.0
...          ...       ...                ...         ...          ...
344534       WLF   Oceania  Wallis and Futuna  2023-10-14       3550.0
345920  OWID_WRL         0              World  2023-10-14  771405394.0
347310       YEM      Asia              Yemen  2023-10-14      11945.0
348695       ZMB    Africa             Zambia  2023-10-14     349287.0
350080       ZWE    Africa           Zimbabwe  2023-10-14     265808.0

        new_cases  new_cases_smoothed  total_deaths  new_deaths  \
1380         41.0              41.286        7951.0         0.0
2765        132.0              40.714      259023.0         0.0
4150          0.0               0.000        3604.0         0.0
5535          0.0               2.429        6881.0         0.0
6920          0.0               0.000          34.0         0.0
...           ...                 ...           ...         ...
344534        0.0               0.000           8.0         0.0
345920     1177.0           14363.429     6972084.0         4.0
347310        0.0               0.000        2159.0         0.0
348695        0.0               0.000        4069.0         0.0
350080        0.0               5.286        5718.0         0.0

        new_deaths_smoothed  ...  male_smokers  handwashing_facilities  \
1380                  0.000  ...         0.000                  37.746
2765                  0.000  ...         0.000                   0.000
4150                  0.000  ...        51.200                   0.000
5535                  0.000  ...        30.400                  83.741
6920                  0.000  ...         0.000                   0.000
...                     ...  ...           ...                     ...
344534                0.000  ...         0.000                   0.000
345920               45.286  ...        34.635                  60.130
347310                0.000  ...        29.200                  49.542
348695                0.000  ...        24.700                  13.938
350080                0.000  ...        30.700                  36.791

        hospital_beds_per_thousand  life_expectancy  human_development_index  \
1380                         0.500            64.83                    0.511
2765                         0.000             0.00                    0.000
4150                         2.890            78.57                    0.795
5535                         1.900            76.88                    0.748
6920                         0.000            73.74                    0.000
...                            ...              ...                      ...
344534                       0.000            79.94                    0.000
345920                       2.705            72.58                    0.737
347310                       0.700            66.12                    0.470
348695                       2.000            63.89                    0.584
350080                       1.700            61.49                    0.571

          population  excess_mortality_cumulative_absolute  \
1380    4.112877e+07                                   0.0
2765    1.426737e+09                                   0.0
4150    2.842318e+06                                   0.0
5535    4.490323e+07                                   0.0
6920    4.429500e+04                                   0.0
...              ...                                   ...
344534  1.159600e+04                                   0.0
345920  7.975105e+09                                   0.0
347310  3.369661e+07                                   0.0
348695  2.001767e+07                                   0.0
350080  1.632054e+07                                   0.0

        excess_mortality_cumulative  excess_mortality  \
1380                            0.0               0.0
2765                            0.0               0.0
4150                            0.0               0.0
5535                            0.0               0.0
6920                            0.0               0.0
...                             ...               ...
344534                          0.0               0.0
345920                          0.0               0.0
347310                          0.0               0.0
348695                          0.0               0.0
350080                          0.0               0.0

        excess_mortality_cumulative_per_million
1380                                        0.0
2765                                        0.0
4150                                        0.0
5535                                        0.0
6920                                        0.0
...                                         ...
344534                                      0.0
345920                                      0.0
347310                                      0.0
348695                                      0.0
350080                                      0.0

[247 rows x 67 columns]

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
344556,OWID_WRL,NaN,World,2020-01-19,137.0,79.0,13.286,6.0,1.0,0.286,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
344557,OWID_WRL,NaN,World,2020-01-20,215.0,78.0,24.286,7.0,1.0,0.429,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
344558,OWID_WRL,NaN,World,2020-01-21,308.0,93.0,36.857,9.0,2.0,0.714,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
344559,OWID_WRL,NaN,World,2020-01-22,456.0,148.0,58.000,20.0,11.0,2.286,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
344560,OWID_WRL,NaN,World,2020-01-23,586.0,133.0,77.000,21.0,1.0,2.429,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345920,OWID_WRL,NaN,World,2023-10-14,771405394.0,1177.0,14363.429,6972084.0,4.0,45.286,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
345921,OWID_WRL,NaN,World,2023-10-15,771407061.0,1667.0,12915.286,6972139.0,55.0,43.857,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
345922,OWID_WRL,NaN,World,2023-10-16,771407061.0,0.0,7955.143,6972139.0,0.0,37.429,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
345923,OWID_WRL,NaN,World,2023-10-17,771407061.0,0.0,4032.429,6972139.0,0.0,21.571,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN
345924,OWID_WRL,NaN,World,2023-10-18,771407061.0,0.0,2243.857,6972139.0,0.0,17.143,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN

array(['Micronesia (country)', 'Niue', 'North America', 'North Korea',
       'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Oceania',
       'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama', 'Paraguay',
       'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda',
       'Saint Barthelemy', 'Saint Helena', 'Saint Kitts and Nevis',
       'Saint Lucia', 'Saint Martin (French part)',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Scotland', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone',
       'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South America', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'United States Virgin Islands', 'Upper middle income', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Vatican', 'Venezuela', 'Vietnam',
       'Wales', 'Wallis and Futuna', 'Western Sahara', 'World', 'Yemen',
       'Zambia', 'Zimbabwe'], dtype=object)

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

<bound method Series.unique of 0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
            ...
350080    265808.0
350081    265808.0
350082    265808.0
350083    265808.0
350084    265808.0
Name: total_cases, Length: 350085, dtype: float64>

np.float64(37.0)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
345298,OWID_WRL,NaN,World,2022-01-30,375307853.0,8401961.0,3346361.0,5715126.0,17569.0,9690.857,...,34.635,60.13,2.705,72.58,0.737,7.975105e+09,NaN,NaN,NaN,NaN

8401961.0

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
350080   NaN
350081   NaN
350082   NaN
350083   NaN
350084   NaN
Name: people_vaccinated_per_hundred, Length: 350085, dtype: float64